version: 2.1
orbs:
  node: circleci/node@5.0.0
  aws-cli: circleci/aws-cli@1.3.1
  eb: circleci/aws-elastic-beanstalk@1.0.0
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - node/install
      - aws-cli/setup
      - eb/setup
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
          name: Api Install
          command: |
            npm run backend:install
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Api Build
          command: |
            npm run backend:build
      - run:
          name: Deploy Front-End
          command: |
            npm run frontend:deploy
      - run:
          name: Deploy Api
          command: |
            npm run backend:deploy

workflows:
    build:
      jobs:
        - build:
            filters:
              branches:
                only:
                  - main
